apiVersion: v1
kind: Service
metadata:
  labels:
    app: app2
  name: app2-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/app2-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
